FROM node:26-alpine AS builder
WORKDIR /app
COPY apps/web/package.json apps/web/package.json
COPY apps/web ./apps/web
WORKDIR /app/apps/web

ARG NEXT_PUBLIC_API_URL=http://localhost:8000
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN npm install --legacy-peer-deps && npm run build

FROM node:26-alpine
WORKDIR /app
COPY --from=builder /app/apps/web/.next ./.next
COPY --from=builder /app/apps/web/package.json ./package.json
EXPOSE 3000
CMD ["npm", "start"]
