FROM node:20-alpine AS builder
WORKDIR /app
COPY apps/web/package.json apps/web/package.json
COPY apps/web ./apps/web
WORKDIR /app/apps/web
RUN npm install --legacy-peer-deps && npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/apps/web/.next ./.next
COPY --from=builder /app/apps/web/package.json ./package.json
EXPOSE 3000
CMD ["npm", "start"]
